/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-07-22 06:54:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>main</title>\n");
      out.write("<link href=\"css/style.css?v=3\" rel =\"stylesheet\" type=\"text/css\">\n");
      out.write("<style>\n");
      out.write("\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("	<script type = \"text/javascript\">\n");
      out.write("		\n");
      out.write("		let i =0;\n");
      out.write("		function changeImg(){\n");
      out.write("			\n");
      out.write("			console.log(\"changeimg 호출 \");\n");
      out.write("			let obj = document.getElementById('intro_img');\n");
      out.write(" 		 	let arr = new Array(\"1.jpg\",\"2.jpg\",\"3.jpg\",\"4.jpg\");	\n");
      out.write(" 		 	obj.src =\"img/\"+arr[i]; \n");
      out.write("			fadeIn2(obj);\n");
      out.write("			i +=1;\n");
      out.write("			if(i==3) {\n");
      out.write("				i=0};			\n");
      out.write("			\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		function fadeIn2(obj){\n");
      out.write("			obj.style.opacity =0;\n");
      out.write("			let tick = function(){\n");
      out.write("				obj.style.opacity = +obj.style.opacity + 0.01;\n");
      out.write("				if(+obj.style.opacity < 1){\n");
      out.write("					(window.requestAnimationFrame && requestAnimationFrame(tick)) || setTimeout(tick,16)\n");
      out.write("				}\n");
      out.write("			};\n");
      out.write("			tick();\n");
      out.write("			\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		 \n");
      out.write("	</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"main\">\n");
      out.write("	<div class=\"main_wrapper\">\n");
      out.write("		<div class=\"main_text\" id =\"main_intro_text\">\n");
      out.write("			자연과 함께하는 기업.   <br> AirShop\n");
      out.write("		</div>\n");
      out.write("		<div>\n");
      out.write("			<img id=\"intro_img\" class=\"main_img\" src=\"img/4.jpg\">	 \n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("	let obj = document.getElementById('intro_img');\n");
      out.write("	let intro_text = document.getElementById('main_intro_text');\n");
      out.write("	 setInterval(changeImg,10000);\n");
      out.write("\n");
      out.write("	const user = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("\n");
      out.write("	if(user!= \"\"){\n");
      out.write("	\n");
      out.write("	let text = document.getElementById('header_title_login');\n");
      out.write("	text.innerHTML = \"로그아웃\";\n");
      out.write("	text.href =\"logout.jsp\"; \n");
      out.write("	}\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
