/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-10-03 11:05:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class order_005fform_005fthird_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<style>\n");
      out.write("\n");
      out.write("	.order_form_third_title{\n");
      out.write("		margin-top : 2rem;\n");
      out.write("		margin-bottom : 2rem;\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	.pay_list{\n");
      out.write("		margin-top : 3rem;\n");
      out.write("		display : flex;\n");
      out.write("		flex-direction : column;\n");
      out.write("		width : 50%;\n");
      out.write("	}\n");
      out.write("	.pay_list div{\n");
      out.write("		margin-bottom : 2rem;\n");
      out.write("		border : 1px solid grey;\n");
      out.write("		width: 70%;\n");
      out.write("		height: 2.5rem;\n");
      out.write("		display: flex;\n");
      out.write("    	justify-content: center;\n");
      out.write("    	align-items: center;\n");
      out.write("	}\n");
      out.write("	.pay_list div:hover{\n");
      out.write("		background :grey;\n");
      out.write("		color :white;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.order_form_third_button{\n");
      out.write("		margin-top :2.3rem;\n");
      out.write("		font-size : 1.1rem;\n");
      out.write("		position : relative;\n");
      out.write("		top : 5.6rem;\n");
      out.write("		width : 100%;\n");
      out.write("		height : 3.2rem;\n");
      out.write("		background : black;\n");
      out.write("		color : white;\n");
      out.write("		text-align : center;\n");
      out.write("	}\n");
      out.write("</style>\n");
      out.write("<div class=\"order_form_third_wrapper\">\n");
      out.write("\n");
      out.write("	<div class=\"order_form_third_title\">\n");
      out.write("		결제수단선택\n");
      out.write("	</div>\n");
      out.write("	<div class=\"pay_list\">\n");
      out.write("		<div>\n");
      out.write("			카카오페이\n");
      out.write("		</div>\n");
      out.write("		<div>\n");
      out.write("			payco\n");
      out.write("		</div>\n");
      out.write("		<div>\n");
      out.write("			NaverPay\n");
      out.write("		</div>\n");
      out.write("		<div>\n");
      out.write("			실시간계좌이체\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	<div class=\"long\">	\n");
      out.write("		<button class=\"order_form_third_button\">결제하기</button>\n");
      out.write("	\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
