/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-07-22 13:48:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class products_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/Users/seungsu/dev/java/carrot/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/carrot/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1620997196000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>products</title>\n");
      out.write("</head>\n");
      out.write("<link href=\"css/style.css?v=2\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<style>\n");
      out.write("\n");
      out.write(".item_wrapper{\n");
      out.write("	margin-top : 4em;\n");
      out.write("	display :grid;\n");
      out.write("	grid-template-columns : 1fr 1fr 1fr;\n");
      out.write("	grid-column-gap : 2em;\n");
      out.write("	grid-row-gap : 2em;\n");
      out.write("}\n");
      out.write(".product_item_textarea{\n");
      out.write("\n");
      out.write("	display :flex;\n");
      out.write("	justify-content: space-between;\n");
      out.write("}\n");
      out.write(".product_item img{\n");
      out.write("	width :380px;\n");
      out.write("	height : 380px;\n");
      out.write("}\n");
      out.write(".product_item_textarea_right span{\n");
      out.write("	display :block;\n");
      out.write("}\n");
      out.write(".product_item{\n");
      out.write("	width: 80%\n");
      out.write("}\n");
      out.write(".product_main{\n");
      out.write("	display :grid;\n");
      out.write("	grid-template-columns : 1fr 6fr;\n");
      out.write("	\n");
      out.write("}\n");
      out.write(".product_title_wrapper{\n");
      out.write("	margin-top : 1em;\n");
      out.write("	margin-bottom : 1em;\n");
      out.write("	width : 100%;\n");
      out.write("	display:flex;\n");
      out.write("	justify-content : center;\n");
      out.write("}\n");
      out.write(".product_title{\n");
      out.write("	\n");
      out.write("	width :94%;\n");
      out.write("	display: flex;\n");
      out.write("	justify-content : space-between;\n");
      out.write("	\n");
      out.write("}\n");
      out.write(".product_title div{\n");
      out.write("	font-size :  3.4em;\n");
      out.write("}\n");
      out.write(".product_aside{\n");
      out.write("	overflow : scroll;\n");
      out.write("	margin-right : 1em;\n");
      out.write("	height: 100%;\n");
      out.write("	display: flex;\n");
      out.write("	flex-direction : column;\n");
      out.write("	align-items : center;\n");
      out.write("	padding : 0 1em 0 1em; \n");
      out.write("}\n");
      out.write(".product_aside_sizebox{\n");
      out.write("	display :grid;\n");
      out.write("	grid-template-columns :1fr 1fr 1fr;\n");
      out.write("	grid-row-gap : 0.3em;\n");
      out.write("	width :100%;\n");
      out.write("}\n");
      out.write(".product_aside_size{\n");
      out.write("	border : 1px solid grey;\n");
      out.write("	border-radius : 0.6em;\n");
      out.write("	color : grey;\n");
      out.write("	width :4em;\n");
      out.write("	height : 2em;\n");
      out.write("	font-size : 0.9em;	\n");
      out.write("}\n");
      out.write(".product_aside_size:hover{\n");
      out.write("	background : grey;\n");
      out.write("	color :white;\n");
      out.write("}\n");
      out.write(".product_aside_title{\n");
      out.write("	margin :1em;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\n");
      out.write("<div class=\"product_title_wrapper\">\n");
      out.write("	<div class=\"product_title\">\n");
      out.write("		<div>Men 신발</div>\n");
      out.write("		<div>필터</div>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("<div class =\"product_main\" style=\"border :1px solid black\">\n");
      out.write("<div class=\"product_aside\">\n");
      out.write("	<div class=\"center product_aside_title\">신발 사이즈</div>\n");
      out.write("	<div class=\"product_aside_sizebox\">\n");
      out.write("		");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("	\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("	<div class=\"item_wrapper\">\n");
      out.write("	\n");
      out.write("		<div class=\"product_item\">\n");
      out.write("			<img src=\"img/shoe_1.png\" alt=\"상품\" />\n");
      out.write("			<div class =\"product_item_textarea\">\n");
      out.write("				<div class=\"product_item_textarea_right\">\n");
      out.write("					<span>나이키 에어맥스</span>\n");
      out.write("					<span>남성 신발 라이프 스타일</span>\n");
      out.write("				</div>\n");
      out.write("				<div>\n");
      out.write("					<span>15,900원</span>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"product_item\">\n");
      out.write("			<img src=\"img/shoe_2.png\" alt=\"상품\" />\n");
      out.write("			<div class =\"product_item_textarea\">\n");
      out.write("				<div class=\"product_item_textarea_right\">\n");
      out.write("					<span>나이키 에어맥스</span>\n");
      out.write("					<span>남성 신발 라이프 스타일</span>\n");
      out.write("				</div>\n");
      out.write("				<div>\n");
      out.write("					<span>15,900원</span>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"product_item\">\n");
      out.write("			<img src=\"img/shoe_3.png\" alt=\"상품\" />\n");
      out.write("			<div class =\"product_item_textarea\">\n");
      out.write("				<div class=\"product_item_textarea_right\">\n");
      out.write("					<span>나이키 에어맥스</span>\n");
      out.write("					<span>남성 신발 라이프 스타일</span>\n");
      out.write("				</div>\n");
      out.write("				<div>\n");
      out.write("					<span>15,900원</span>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"product_item\">\n");
      out.write("			<img src=\"img/shoe_4.png\" alt=\"상품\" />\n");
      out.write("			<div class =\"product_item_textarea\">\n");
      out.write("				<div class=\"product_item_textarea_right\">\n");
      out.write("					<span>나이키 에어맥스</span>\n");
      out.write("					<span>남성 신발 라이프 스타일</span>\n");
      out.write("				</div>\n");
      out.write("				<div>\n");
      out.write("					<span>15,900원</span>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"product_item\"></div>\n");
      out.write("		<div class=\"product_item\"></div>\n");
      out.write("		<div class=\"product_item\"></div>\n");
      out.write("		<div class=\"product_item\"></div>\n");
      out.write("		<div class=\"product_item\"></div>\n");
      out.write("	\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("</div>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /products.jsp(100,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("i");
      // /products.jsp(100,2) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setBegin(220);
      // /products.jsp(100,2) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setEnd(290);
      // /products.jsp(100,2) name = step type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setStep(5);
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("		<div class=\"product_aside_size center\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\n");
            out.write("		");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
